---
# weave of testing:
#  yamllint
#  ansible-playbook --syntax-check
#  ansible-lint
#  molecule test (integration)
#  ansible-playbook --check (against prod)
#  parallel infra!
#
#
# https://docs.gitlab.com/ee/ci/yaml/#image
# https://github.com/ansible-community/toolset
# https://quay.io/repository/ansible/toolset?tab=tags
image: quay.io/ansible/toolset:main
# image: quay.io/ansible/molecule:latest

# https://docs.gitlab.com/ee/ci/yaml/#services
# https://stackoverflow.com/a/48727996
services:
  - docker:dind

# https://docs.gitlab.com/ee/ci/yaml/#stages
stages:
  - lint
  - converge
  - verify

# https://docs.gitlab.com/ee/ci/yaml/#before_script
before_script:
  - python -V
  - ansible --version
  - molecule --version
  - docker -v
  - pwd
  - ls -l
  - molecule create
  - molecule list

#
# LINT
#
# Lint - cent
molecule:lint:centos6:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-centos6-ansible
  script:
    - molecule lint

molecule:lint:centos7:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-centos7-ansible
  script:
    - molecule lint

molecule:lint:centos8:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-centos8-ansible
  script:
    - molecule lint

# Lint - debian
molecule:lint:debian7:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-debian7-ansible
  script:
    - molecule lint

molecule:lint:debian8:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-debian8-ansible
  script:
    - molecule lint

molecule:lint:debian9:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-debian9-ansible
  script:
    - molecule lint

molecule:lint:debian10:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-debian10-ansible
  script:
    - molecule lint
    
molecule:lint:debian11:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-debian11-ansible
  script:
    - molecule lint

# Lint - ubuntu
molecule:lint:ubuntu1204:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-ubuntu1204-ansible
  script:
    - molecule lint

molecule:lint:ubuntu1404:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-ubuntu1404-ansible
  script:
    - molecule lint

molecule:lint:ubuntu1604:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-ubuntu1604-ansible
  script:
    - molecule lint

molecule:lint:ubuntu1804:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-ubuntu1804-ansible
  script:
    - molecule lint

molecule:lint:ubuntu2004:
  stage: lint
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    MOLECULE_DISTRO: geerlingguy/docker-ubuntu2004-ansible
  script:
    - molecule lint

# Converge
molecule:converge:
  stage: converge
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    - molecule converge


molecule:verify:
  stage: verify
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    - molecule verify

# a gitlab stage per molecule scenario
# https://docs.gitlab.com/ee/ci/yaml/#stages
# https://molecule.readthedocs.io/en/latest/ci.html#gitlab-ci
# molecule-el7-testing:
#   stage: test
#   variables:
#     DOCKER_HOST: "tcp://docker:2375"
#   script:
#     - molecule converge
#     - molecule idempotence
#     - molecule destroy
#   only:
#     changes:
#       - ./*/*
#       - .gitlab-ci.yml

# a gitlab stage per molecule scenario
# https://docs.gitlab.com/ee/ci/yaml/#stages
# molecule-el8-testing:
#   stage: test
#   variables:
#     DOCKER_HOST: "tcp://docker:2375"
#     PY_COLORS: 1
#   script:
#     - molecule converge -s el8
#     - molecule idempotence -s el8
#     - molecule destroy -s el8
#   only:
#     changes:
#       - ./*/*
#       - .gitlab-ci.yml
