---
# weave of testing:
#  yamllint
#  ansible-playbook --syntax-check
#  ansible-lint
#  molecule test (integration)
#  ansible-playbook --check (against prod)
#  parallel infra!
#
#
# https://docs.gitlab.com/ee/ci/yaml/#image
# https://github.com/ansible-community/toolset
# https://quay.io/repository/ansible/toolset?tab=tags
image: quay.io/ansible/toolset:main
# image: quay.io/ansible/molecule:latest

# https://docs.gitlab.com/ee/ci/yaml/#services
# https://stackoverflow.com/a/48727996
services:
  - docker:dind

variables:
  #DOCKER_HOST: "tcp://docker:2375"
  DOCKER_HOST: "tcp://localhost:2375"
  PY_COLORS: 1
  IMG_CENTOS7: geerlingguy/docker-centos7-ansible
  IMG_CENTOS8: geerlingguy/docker-centos8-ansible
  IMG_DEBIAN8: geerlingguy/docker-debian8-ansible
  IMG_DEBIAN9: geerlingguy/docker-debian9-ansible
  IMG_DEBIAN10: geerlingguy/docker-debian10-ansible
  IMG_DEBIAN11: geerlingguy/docker-debian11-ansible
  IMG_UBUNTU1604: geerlingguy/docker-ubuntu1604-ansible
  IMG_UBUNTU1804: geerlingguy/docker-ubuntu1804-ansible
  IMG_UBUNTU2004: geerlingguy/docker-ubuntu2004-ansible

# https://docs.gitlab.com/ee/ci/yaml/#stages
stages:
  - lint
  - converge
  - verify

# https://docs.gitlab.com/ee/ci/yaml/#before_script
before_script:
  - python -V
  - ansible --version
  - molecule --version
  - docker -v
  - pwd
  - ls -l
  - molecule create
  - molecule list

.docker_runner: &docker_runner
  script:
    - echo "Running"
#  tags:
#    - aks-docker-runner

#
# LINT
#
# Lint - centos
molecule:lint:centos7:
  <<: *docker_runner
  stage: lint
  variables:
    MOLECULE_DISTRO: $IMG_CENTOS7
  script:
    - molecule lint

# eof
