---
language: python
python: "2.7"

env:
  matrix:
    # RPM
    - MOLECULE_DISTRO: centos:6
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:8
    - MOLECULE_DISTRO: centos:9
    # DEB
    - MOLECULE_DISTRO: debian:8
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: debian:10
    - MOLECULE_DISTRO: debian:11
    # 
    # - MOLECULE_DISTRO: fedora:27
    # - MOLECULE_DISTRO: fedora:28
    # - MOLECULE_DISTRO: ubuntu-upstart:trusty
    # - MOLECULE_DISTRO: ubuntu:xenial
    # - MOLECULE_DISTRO: ubuntu:bionic
    # - MOLECULE_DISTRO: debian:jessie
    # - MOLECULE_DISTRO: debian:stretch

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
