---
- name: Syslog configuration
  lineinfile:
    path: /etc/rsyslog.d/100-local.conf
    state: present
    line: '*.*    /var/log/all.log'
    create: true

- name: Enable rsyslog statistics
  copy:
    content:
      module(load="impstats" interval="60" severity="7" resetCounters="on" format="cee")
    dest: /etc/rsyslog.d/12-stats.conf
    owner: root
    group: root
    mode: 0400

- name: Log rotation for Debian
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    state: present
    insertbefore: BOF
    line: /var/log/all.log
  when: ansible_distribution == "Debian"

- name: Log roration for RedHat
  lineinfile:
    path: /etc/logrotate.d/syslog
    state: present
    insertbefore: BOF
    line: /var/log/all.log
  when: ansible_distribution == "RedHat"

- name: Log roration for SLES
  lineinfile:
    path: /etc/logrotate.d/syslog
    state: present
    insertbefore: '^\/var\/log\/warn'
    line: /var/log/all.log
  when: ansible_distribution == "SLES"

- name: Log roration for Ubuntu
  lineinfile:
    path: /etc/logrotate.d/syslog
    state: present
    insertbefore: '^\/var\/log\/warn'
    line: /var/log/all.log
  when: ansible_distribution == "ubuntu"

- name: Log roration for OracleLinux
  lineinfile:
    path: /etc/logrotate.d/syslog
    state: present
    insertbefore: '^\/var\/log\/spooler'
    line: /var/log/all.log
  when: ansible_distribution == "OracleLinux"

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
