---
- name: Prepare
  hosts: all
  tasks:
    - name: Install OpenSSH server
      package:
        name:
          - openssh
          - openssh-server
          - rsyslog
          - rsyslogd
      ignore_errors: true
    - name: Start OpenSSH daemon
      service:
        name: "{{ item }}"
        state: started
      loop:
          - openssh
          - openssh-server
          - rsyslog
          - rsyslogd
      ignore_errors: true
