---
- name: Prepare
  hosts: all
  tasks:
    - name: Install OpenSSH server
      package:
        name:
          - openssh
          - openssh-server
      ignore_errors: true
    - name: Start OpenSSH daemon
      service:
        name: sshd
        state: started
      ignore_errors: true
