---
- name: Prepare
  hosts: all
  tasks:
    - name: Install OpenSSH server
      package:
        name:
          - openssh
          - openssh-server
          - rsyslog
    - name: Start OpenSSH daemon
      service:
        name: sshd
        state: started
    - name: Install rsyslog
      service:
        name: rsyslog
        state: started

