---
- name: Prepare
  hosts: all
  tasks:
    - name: ansible_distribution
      debug:
        msg: "Linux distribution {{ ansible_distribution }}"

    - name: Install OpenSSH server
      yum:
        name:
          - openssh
          - openssh-server
          - rsyslog
        state: present
        update_cache: true
      when: (ansible_distribution | lower)
        in ("redhat", "sles", "oraclelinux", "centos")

    - name: Install OpenSSH Client
      apt:
        name:
          - openssh-client
          - openssh-server
          - rsyslog
        update_cache: true
      when: (ansible_distribution | lower) in ("ubuntu", "debian")

    - name: Start OpenSSH daemon
      service:
        name: sshd
        state: started

    - name: Install rsyslog
      service:
        name: rsyslog
        state: started
